[package]
name = "jet-simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
bincode = "1.3"
bytemuck = "1"
futures = "0.3"
parking_lot = "0.12"
rand = "0.7"
lazy_static = "1"
dlopen = "0.1.8"
tokio = { version = "1", features = ["rt"] }

solana-account-decoder = "1.11.5"
solana-client = "1.11.5"
solana-sdk = "1.11.5"
solana-transaction-status = "1.11.5"
solana-runtime = "1.11.5"
solana-program-runtime = "1.11.5"
solana-bpf-loader-program = "1.11.5"
solana-program-test = "1.11.5"
