name: Test

on:
  pull_request: {}
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Cache Cargo
        uses: actions/cache@v2
        id: cache-cargo-build
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: cargo-${{ runner.os }}-cargo-build-${{ hashFiles('./Cargo.lock') }}

      - name: Format Check
        run: cargo fmt --all --check

      - name: Clippy Check
        run: cargo clippy --all-targets -- -Dwarnings

      - name: Tests
        run: cargo test
